// Promotions
#static_assert(typeof(+char(0)) == typeof(int))
#static_assert(typeof(+uchar(0)) == typeof(int))
#static_assert(typeof(+schar(0)) == typeof(int))
#static_assert(typeof(+short(0)) == typeof(int))
#static_assert(typeof(+ushort(0)) == typeof(int))
#static_assert(typeof(+int(0)) == typeof(int))
#static_assert(typeof(+uint(0)) == typeof(uint))
#static_assert(typeof(+long(0)) == typeof(long))
#static_assert(typeof(+ulong(0)) == typeof(ulong))
#static_assert(typeof(+llong(0)) == typeof(llong))
#static_assert(typeof(+ullong(0)) == typeof(ullong))
#static_assert(typeof(+float(0)) == typeof(float))
#static_assert(typeof(+double(0)) == typeof(double))

// Conversions
#static_assert(typeof(uchar(0) + uchar(0)) == typeof(int))
#static_assert(typeof(short(0) + ushort(0)) == typeof(int))
#static_assert(typeof(int(0) + uint(0)) == typeof(uint))
#static_assert(typeof(int(0) + long(0)) == typeof(long))
#static_assert(typeof(int(0) + float(0)) == typeof(float))
#static_assert(typeof(int(0) + double(0)) == typeof(double))
#static_assert(typeof(float(0) + double(0)) == typeof(double))
#static_assert(typeof(float(0) + float(0)) == typeof(float))
#static_assert(typeof(double(0) + double(0)) == typeof(double))
